### ISSUE TITLE
Running in Edge Development Mode without Docker

### ISSUE THREAD

**Issue by mukeshnikhil2000** [Sitecore/XM-Cloud-Introduction#261] opened 2023-05-26 17:50 UTC
Docker is not allowed in my organization and we want to use XM Cloud.
Any idea when are you providing full set up that can be done on local machine connecting to XM Cloud CM ENV without docker and deploying from local to XM Cloud without docker

**Comment by robearlam** [comment] 2023-05-29 00:11
Closing as this is a duplicate of #178

**Closed by robearlam** 2023-05-29 00:11 UTC
Labels: enhancement
