### ISSUE TITLE
Sitecore MVP directory is not showing profile pic

### ISSUE THREAD

**Issue by gauravpansari1991** [Sitecore/XM-Cloud-Introduction#346] opened 2024-02-14 06:42 UTC
Describe the bug
The profile picture is not showing on the MVP website

To Reproduce

Go to 'https://mvp.sitecore.com/Directory'
Search for 'Gaurav'
It will show a card without a Profile pic
I have already set Profile Photo Source to Gravatar, previously it was set to Twitter as well but still no image 

Expected behavior
It should show a card with a profile pic

<img width="1104" alt="image" src="https://github.com/Sitecore/XM-Cloud-Introduction/assets/12952868/22b1dca2-299f-4fc1-b7bb-fc821aeb96a6">

**Comment by sc-ivanlieckens** [comment] 2024-02-14 08:43
Closing as duplicate of #348

**Closed by sc-ivanlieckens** 2024-02-14 08:43 UTC
Labels: bug, MVP Site
