### ISSUE TITLE
Running in Edge Development Mode without Docker

### ISSUE THREAD

**Issue by mukeshnikhil2000** [Sitecore/XM-Cloud-Introduction#250] opened 2023-04-18 01:35 UTC
When is the doc getting updated for "Running in Edge Development Mode without Docker"?

I am having issue with Docker and not allowed Docker in my org.

**Comment by robearlam** [comment] 2023-04-18 04:23
Currently, it is a manual process of populating the NextJS env files, or .NET Application.json with your Edge details then manually running the site either via NPM, DotNet CLI, or Visual Studio.

Closing issue this as a duplicate of #178, which is already tracking the automation of this functionality.

**Closed by robearlam** 2023-04-18 04:23 UTC
Labels: enhancement
